### ISSUE TITLE
Move to rbenv organisation?

### ISSUE THREAD

**Issue by Ivoz** [rkh/rbenv-update#37]
I find this is a pretty simple yet useful plugin. It could be worth making it officially part of the rbenv umbrella.

Have you considered moving it to rbenv and asking to become a team member to continue maintaining it? I think doing so makes a lot of sense, but I might be missing something.

Any thoughts @sstephenson ? Cheers!

**Comment by olivierlacan** [comment]
This plugin is listed as approved in https://github.com/rbenv/rbenv/wiki/Plugins#approved-plugins today. But I'd agree there's a visibility problem with depending on plugins many (most) people may not know about for functionality that should arguably be in rbenv core.

But if it's not complexity the rbenv maintainers want to take on themselves, then that's something we (as users) should respect.

**Comment by jasonkarns** [comment]
As it hasn't happened yet, I doubt it will.

**Comment by jasonkarns** [comment]
But for posterity: https://github.com/rbenv/rbenv/issues/301
